{{- if and .Values.networkPolicy.enabled (gt (len .Values.networkPolicy.policies) 0) }}
{{- range $i, $policy := .Values.networkPolicy.policies }}
{{- $policyName := default (printf "np-%d" $i) $policy.name }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ printf "%s-%s" (include "driftd.fullname" $) $policyName | trunc 63 | trimSuffix "-" }}
  labels:
    app.kubernetes.io/name: {{ include "driftd.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
  {{- with $policy.annotations }}
  annotations:
{{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  podSelector:
  {{- if $policy.podSelector }}
{{ toYaml $policy.podSelector | nindent 4 }}
  {{- else }}
    {}
  {{- end }}
  {{- with $policy.policyTypes }}
  policyTypes:
{{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with $policy.ingress }}
  ingress:
{{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with $policy.egress }}
  egress:
{{ toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- end }}
