apiVersion: v2
name: driftd
description: Terraform/Terragrunt drift detection server
version: 0.1.1
appVersion: "v0.1.1"

dependencies:
  - name: redis
    version: ~20.x
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
